// Generated by CoffeeScript 1.6.3
(function() {
  var h, helpers, jsFn, m, utils, _,
    __slice = [].slice;

  _ = require('lodash');

  utils = require('./utils');

  m = (function() {
    var mori, out;
    mori = require('mori');
    out = {};
    _.each(mori, function(v, k) {
      var key;
      key = utils.kamelKey(k);
      return out[key] = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return mori[k].apply(mori, args);
      };
    });
    return out;
  })();

  jsFn = _.curry(function(fn, x) {
    return fn(m.cljToJs(x));
  });

  helpers = h = {
    inspect: jsFn(utils.inspect),
    assocX: function(target, k, v) {
      if (_.isArray(k)) {
        return m.assocIn(target, k, v);
      }
      return m.assoc(target, k, v);
    },
    getX: function(target, k) {
      if (_.isString(k)) {
        k = utils.keyString(k);
      }
      if (_.isArray(k)) {
        return m.getIn(target, k);
      }
      return m.get(target, k);
    }
  };

  _.extend(m, helpers);

  module.exports = m;

}).call(this);
